# Docker Compose configuration for running the backend locally.
# This setup runs the backend in development mode using Dockerfile.dev,
# and includes PostgreSQL and Redis containers connected to the backend.


